# Generated by Django 3.1.7 on 2021-04-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210418_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
